# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a706aed7f4c84f3b29f4338f6387a1ef004d8e999ac4d7395f5173807c136ceb406c97f852e110e8a756a67c429231137e853ddcd9cd4afa151c8271cc8fcbe9

test:
  secret_key_base: dd8fc024e551158b7553a920c74aa8777032cd6e5bad9282746f2267630da11303d8aef38cefbfd2f309617199f6162897a56cc29e2efde18c8499333f60656c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
